version: "3.8"

services:
    deepstream61:
        image: maximofn/deepstream61:dev

        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        
        command: tail -f /dev/null

        volumes:
          - ../../deepstream_apps:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_apps
          - ../../deepstream_nano:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_nano

        ports:
          - "8554:8554"