version: "3.8"

services:
    deepstream61:
        image: maximofn/deepstream61:dev

        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
                
        runtime: nvidia
        
        command: tail -f /dev/null

        volumes:
          - /tmp/.X11-unix/:/tmp/.X11-unix/
          - ../../deepstream_apps:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_apps
          - ../../deepstream_nano:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_nano
        
        devices:
          - "/dev/video0:/dev/video0"

        ports:
          - "8554:8554"