version: "3.8"

services:
  deepstream61:
    container_name: deepstream61
    image: maximofn/deepstream61:dev
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    # command: tail -f /dev/null
    command: jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --no-browser
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ../deepstream_apps:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_apps
      - ../deepstream_nano:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_nano
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "8554:8554"
      - "8888:8888"