version: "3.8"

services:
  tensorrt:
    container_name: tensorrt
    image: maximofn/tensorrt:pytorch
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    # command: tail -f /dev/null
    command: jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --no-browser
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ../volumen:/workspace
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "8888:8888"